# Generated by Django 2.2.12 on 2020-05-17 05:05

from django.db import migrations

# from students.models import Student


def forwards(apps, schema):
    print('forwards!')
    Student = apps.get_model('students', 'Student')

    def inc_age(instance):
        instance.age += 1
        instance.save()

    for student in Student.objects.all().only('phone', 'age').iterator():  # LIMIT OFFSET
        student.phone = ''.join(i for i in student.phone if i.isdigit())
        inc_age(student)
        student.save(update_fields=['phone'])


def backwards(app, schema):
    print('backwards\n' * 10)


class Migration(migrations.Migration):
    dependencies = [
        ('students', '0003_student_phone'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
