# Generated by Django 2.2.12 on 2020-05-17 08:42

from django.db import migrations


def forwards(apps, schema):
    Student = apps.get_model('students', 'Student')

    def first_name_capitalize(instance):
        instance.first_name = instance.first_name.capitalize()

    def last_name_capitalize(instance):
        instance.last_name = instance.last_name.capitalize()

    for student in Student.objects.all().only('first_name', 'first_name').iterator():
        first_name_capitalize(student)
        last_name_capitalize(student)
        student.save(update_fields=['first_name', 'first_name'])


def backwards(app, schema):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('students', '0004_auto_20200517_0505'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
