# Generated by Django 2.2.12 on 2020-05-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200517_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='', max_length=24)),
                ('path', models.CharField(default='', max_length=512)),
                ('execution_time', models.CharField(max_length=128)),
            ],
        ),
    ]
