# Generated by Django 2.2.12 on 2020-05-17 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_logger'),
    ]

    operations = [
        migrations.AddField(
            model_name='logger',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
