# Generated by Django 2.2.12 on 2020-05-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20200509_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.IntegerField(choices=[[1, 'PHP'], [2, 'Java'], [3, 'Python'], [4, 'Ruby'], [5, 'C++'], [6, 'Rust'], [7, 'Swift'], [8, 'Linux'], [9, 'Windows Server']], default=3),
        ),
    ]
