# Generated by Django 2.2.12 on 2020-05-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20200510_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.CharField(choices=[[1, 'PHP'], [2, 'Java'], [3, 'Python'], [4, 'Ruby'], [5, 'C++'], [6, 'Rust'], [7, 'Swift'], [8, 'Linux'], [9, 'Windows Server']], default='Introduction', max_length=32),
        ),
    ]
