# Generated by Django 2.2.12 on 2020-05-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20200510_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='course',
            field=models.CharField(choices=[['PHP', 'PHP'], ['Java', 'Java'], ['Python', 'Python'], ['Ruby', 'Ruby'], ['Rust', 'Rust'], ['Swift', 'Swift'], ['Linux', 'Linux'], ['Introduction', 'Introduction']], default='Introduction', max_length=32),
        ),
    ]
