# Generated by Django 2.2.12 on 2020-05-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_auto_20200510_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default='', max_length=24),
        ),
    ]
