# Generated by Django 2.2.12 on 2020-05-17 08:27

from django.db import migrations


def forwards(apps, schema):
    Teacher = apps.get_model('teachers', 'Teacher')

    def first_name_capitalize(instance):
        instance.first_name = instance.first_name.capitalize()

    def last_name_capitalize(instance):
        instance.last_name = instance.last_name.capitalize()

    for teacher in Teacher.objects.all().only('first_name', 'first_name').iterator():
        first_name_capitalize(teacher)
        last_name_capitalize(teacher)
        teacher.save(update_fields=['first_name', 'first_name'])


def backwards(app, schema):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('teachers', '0008_teacher_phone'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
