# Generated by Django 2.2.12 on 2020-05-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=32)),
                ('created_group', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
