# Generated by Django 2.2.12 on 2020-05-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='theme',
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.IntegerField(choices=[[1, 'PHP'], [2, 'Java'], [3, 'Python'], [4, 'Ruby'], [5, 'C++'], [6, 'Rust'], [7, 'Swift'], [8, 'Linux'], [9, 'Windows Server']], default=3),
        ),
        migrations.AddField(
            model_name='group',
            name='number_students_in_group',
            field=models.CharField(default=14, max_length=2),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_group',
            field=models.DateTimeField(default=''),
        ),
    ]
