# Generated by Django 2.2.12 on 2020-05-10 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20200510_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='created_group',
        ),
        migrations.AddField(
            model_name='group',
            name='start_group',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.CharField(choices=[['PHP', 'PHP'], ['Java', 'Java'], ['Python', 'Python'], ['Ruby', 'Ruby'], ['Rust', 'Rust'], ['Swift', 'Swift'], ['Linux', 'Linux'], ['Introduction', 'Introduction']], default='Introduction', max_length=32),
        ),
    ]
