# Generated by Django 2.2.12 on 2020-05-10 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20200510_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.CharField(choices=[['PHP', 'PHP'], ['Java', 'Java'], ['Python', 'Python'], ['Ruby', 'Ruby'], ['Rust', 'Rust'], ['Swift', 'Swift'], ['Linux', 'Linux'], ['Introduction', 'Introduction']], default='Introduction', max_length=32, verbose_name='Course name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='number_students_in_group',
            field=models.CharField(default=14, max_length=2, verbose_name='Person in group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_group',
            field=models.DateField(default=datetime.date.today, verbose_name='Start date, example: 2020-12-24'),
        ),
    ]
