# Generated by Django 2.2.12 on 2020-05-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_group_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='head',
        ),
    ]
