# Generated by Django 2.2.12 on 2020-05-24 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_group_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='students.Student'),
        ),
    ]
